# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title       : "Henry Dong"
description : "Focusing on wireless communications."
url         : "https://blog.990405.xyz"
baseurl     : ""
repository  : "HenryDong99/HenryDong99.github.io"
lang        : "en"
locale      : "en_US"
theme       :

# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification :  # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name          : "Henry Dong"
  avatar        : "images/profile.png"
  bio           : "NKLWC"
  location      : "Singapore"
  googlescholar : "https://scholar.google.com/citations?user=oWU8V9cAAAAJ"
  github        : "HenryDong99"


# Reading Files
include:
  - _pages
exclude:
  - .bundle
  - .DS_Store
  - .github
  - .jekyll-cache
  - .sass-cache
  - .vscode
  - _site
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - push.sh
  - run_server.sh
  - vendor
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true
  # _notes
  - scope:
      path: ""
      type: notes
    values:
      layout: note
      author_profile: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Singapore


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
